### ISSUE TITLE
A lot of modules(dependencies) are missing

### ISSUE THREAD

**Issue by sakshamsaxena** [enuggetry/jb-galaxy-blaster#3]
While lifting sails, it keeps throwing errors regarding not finding modules. How is it working on yours? 
@pupudu, did you encounter this as well ?

**Comment by sakshamsaxena** [comment]
Kue, Kue-ui, and cors packages were required apparently, and it lifted alright. But the JBrowse isn't there on localhost:1337. Where to browse it?

**Comment by enuggetry** [comment]
I use apache for JBrowse now on port 80.

**Comment by sakshamsaxena** [comment]
You mention in Readme that " (project files will override JBrowse files, copied manually) ". What exactly is copied to where?

**Comment by enuggetry** [comment]
Index.html, a few files in src dir, mainly.

On Jul 11, 2016 4:03 AM, "Saksham Saxena" notifications@github.com wrote:

You mention in Readme that " (project files will override JBrowse files,
copied manually) ". What exactly is copied to where?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/enuggetry/jb-galaxy-blaster/issues/3#issuecomment-231704799,
or mute the thread
https://github.com/notifications/unsubscribe/AJlnAQL9EZreKmm2WIZJw7YFa192DHymks5qUiLmgaJpZM4JEFCV
.
